export const GET_TOKENS = 'GET_TOKENS'
export const TOKENS_UPDATED = 'TOKENS_UPDATED'

export const GET_FEES = 'GET_FEES'
export const FEES_UPDATED = 'FEES_UPDATED'

export const ISSUE_TOKEN = 'ISSUE_TOKEN'
export const TOKEN_ISSUED = 'TOKEN_ISSUED'

export const FINALIZE_TOKEN = 'FINALIZE_TOKEN'
export const TOKEN_FINALIZED = 'TOKEN_FINALIZED'

export const SWAP_TOKEN = 'SWAP_TOKEN'
export const TOKEN_SWAPPED = 'TOKEN_SWAPPED'

export const FINALIZE_SWAP_TOKEN = 'FINALIZE_SWAP_TOKEN'
export const TOKEN_SWAP_FINALIZED = 'TOKEN_SWAP_FINALIZED'

export const LIST_TOKEN = 'LIST_TOKEN'
export const TOKEN_LISTED = 'TOKEN_LISTED'

export const FINALIZE_LIST_TOKEN = 'FINALIZE_LIST_TOKEN'
export const TOKEN_LIST_FINALIZED = 'TOKEN_LIST_FINALIZED'

export const ERROR = 'ERROR'
