export const GET_TOKENS = 'GET_TOKENS'
export const TOKENS_UPDATED = 'TOKENS_UPDATED'

export const GET_FEES = 'GET_FEES'
export const FEES_UPDATED = 'FEES_UPDATED'

export const ISSUE_TOKEN = 'ISSUE_TOKEN'
export const TOKEN_ISSUED = 'TOKEN_ISSUED'

export const FINALIZE_TOKEN = 'FINALIZE_TOKEN'
export const TOKEN_FINALIZED = 'TOKEN_FINALIZED'

export const SWAP_TOKEN = 'SWAP_TOKEN'
export const TOKEN_SWAPPED = 'TOKEN_SWAPPED'

export const FINALIZE_SWAP_TOKEN = 'FINALIZE_SWAP_TOKEN'
export const TOKEN_SWAP_FINALIZED = 'TOKEN_SWAP_FINALIZED'

export const SUBMIT_LIST_PROPOSAL = 'SUBMIT_LIST_PROPOSAL'
export const LIST_PROPOSAL_SUBMITTED = 'LIST_PROPOSAL_SUBMITTED'

export const FINALIZE_LIST_PROPOSAL = 'FINALIZE_LIST_PROPOSAL'
export const LIST_PROPOSAL_FINALIZED = 'LIST_PROPOSAL_FINALIZED'

export const LIST_TOKEN = 'LIST_TOKEN'
export const TOKEN_LISTED = 'TOKEN_LISTED'

export const GET_LIST_PROPOSAL = 'GET_LIST_PROPOSAL'
export const LIST_PROPOSAL_UPDATED = 'LIST_PROPOSAL_UPDATED'

export const ERROR = 'ERROR'
