export const GET_TOKENS = 'GET_TOKENS'
export const TOKENS_UPDATED = 'TOKENS_UPDATED'

export const GET_FEES = 'GET_FEES'
export const FEES_UPDATED = 'FEES_UPDATED'

export const ISSUE_TOKEN = 'ISSUE_TOKEN'
export const TOKEN_ISSUED = 'TOKEN_ISSUED'

export const FINALIZE_TOKEN = 'FINALIZE_TOKEN'
export const TOKEN_FINALIZED = 'TOKEN_FINALIZED'

export const SWAP_TOKEN = 'SWAP_TOKEN'
export const TOKEN_SWAPPED = 'TOKEN_SWAPPED'

export const FINALIZE_SWAP_TOKEN = 'FINALIZE_SWAP_TOKEN'
export const TOKEN_SWAP_FINALIZED = 'TOKEN_SWAP_FINALIZED'

export const SUBMIT_LIST_PROPOSAL = 'SUBMIT_LIST_PROPOSAL'
export const LIST_PROPOSAL_SUBMITTED = 'LIST_PROPOSAL_SUBMITTED'

export const FINALIZE_LIST_PROPOSAL = 'FINALIZE_LIST_PROPOSAL'
export const LIST_PROPOSAL_FINALIZED = 'LIST_PROPOSAL_FINALIZED'

export const LIST_TOKEN = 'LIST_TOKEN'
export const TOKEN_LISTED = 'TOKEN_LISTED'

export const GET_LIST_PROPOSAL = 'GET_LIST_PROPOSAL'
export const LIST_PROPOSAL_UPDATED = 'LIST_PROPOSAL_UPDATED'

export const GET_BNB_BALANCES = 'GET_BNB_BALANCES'
export const BNB_BALANCES_UPDATED = 'BNB_BALANCES_UPDATED'

export const GET_ETH_BALANCES = 'GET_ETH_BALANCES'
export const ETH_BALANCES_UPDATED = 'ETH_BALANCES_UPDATED'

export const CREATE_BNB_ACCOUNT = 'CREATE_BNB_ACCOUNT'
export const BNB_ACCOUNT_CREATED = 'BNB_ACCOUNT_CREATED'

export const GET_ERC20_INFO = 'GET_ERC20_INFO'
export const ERC20_INFO_UPDATED = 'ERC20_INFO_UPDATED'

export const DOWNLOAD_BNB_KEYSTORE = 'DOWNLOAD_BNB_KEYSTORE'
export const BNB_KEYSTORE_DOWNLOADED = 'BNB_KEYSTORE_DOWNLOADED'

export const ERROR = 'ERROR'
